### PR TITLE
feat: formatting check in CI

### PR DESCRIPTION
**Pull request by hamirmahal**

### CODE REVIEW

**Comment by hamirmahal** [comment]
## Summary


This change checks for file formatting discrepancies.

**Comment by hamirmahal** [comment]
## Test Plan


https://github.com/hamirmahal/ruff-vscode/actions/runs/8489292483/job/23259217057

**Review by hamirmahal — COMMENTED** [review]
Let me know your thoughts on this type of change. I was also thinking about adding a similar check for linting errors.

**Comment by MichaReiser** [comment]
Thank you

**Comment by hamirmahal** [comment]
You’re welcome.

**Pull request merged**
