### PR TITLE
refactor: rearrange where formatting check takes place

### PR DESCRIPTION
**Pull request by hamirmahal**

### CODE REVIEW

**Comment by hamirmahal** [comment]
## Summary

This pull request reverts a separate workflow I added in #437 that checks for formatting issues, and then adds that check back in a much cleaner way.

The purpose of this change is to simplify things and improve maintainability.


## Test Plan

CI

**Comment by hamirmahal** [comment]
# Without this change

image

# With this change

image

**Comment by charliermarsh** [comment]
Makes sense, thanks.

**Comment by hamirmahal** [comment]
You're welcome!

**Pull request merged**
