### PR TITLE
Integrate pre-release features into stable

### PR DESCRIPTION
**Pull request by snowsignal**
Note: this does not bump the version or create a new changelog entry. The goal of this PR is to integrate the changes made in the pre-release branch into the stable version for an upcoming release.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Why "beta server" over "experimental server" terminology?

**Comment by snowsignal** [comment]
@charliermarsh I just thought the terminology could use a refresh now that the server has made significant improvements (and will soon become the new default).

**Comment by charliermarsh** [comment]
@snowsignal - Changing the terminology seems reasonable, but I'd suggest picking something that's separate from the stability milestone. It kind of paints us into a corner. For example, what if we make the server opt-out once it stabilizes, but leave the setting in-place to facilitate that opt-out? We'll no longer be in the beta, but the setting would still be called `betaServer`... Or we'd have to rename it, which will require deprecation, etc.

What about `nativeServer` or something inherently related to the server, rather than the stability of it?

**Comment by snowsignal** [comment]
@charliermarsh I like `nativeServer`!

**Review by charliermarsh — COMMENTED** [review]
Overall LGTM, with the exception of changing to `nativeServer` terminology.

**Pull request merged**
